version: '2.1'

services:
  nerds-vs-sicarios:
    container_name: nerds-vs-sicarios
    build: .
    ports:
      - '8090:8090'
    restart: always
    healthcheck:
      test: exit 0
    links:
      - base-de-datos
    depends_on:
      - base-de-datos
  base-de-datos:
    container_name: base-de-datos
    image: mongo
    restart: always
    command: mongod --port 27018
    ports:
        - '27018:27018'